// Generated by CoffeeScript 2.4.1
(function() {
  var Catalog_Interface;

  Catalog_Interface = class Catalog_Interface {
    static insert(catalog) {
      return global[catalog.name] = catalog;
    }

    static find(catalog_name) {
      return global[catalog_name];
    }

  };

  exports.Catalog_Interface = Catalog_Interface;

}).call(this);
