// Generated by CoffeeScript 2.4.1
(function() {
  var Good_Interface;

  Good_Interface = class Good_Interface {
    static insert(good) {
      return global.all_goods[good.name] = good;
    }

    static find(good_name) {
      return global.all_goods[good_name];
    }

  };

  exports.Good_Interface = Good_Interface;

}).call(this);
