// Generated by CoffeeScript 2.4.1
(function() {
  var Item_Interface;

  Item_Interface = class Item_Interface {
    static insert(item) {
      return global.all_items[item.name] = item;
    }

    static find(item_name) {
      return global.all_items[item_name];
    }

  };

  exports.Item_Interface = Item_Interface;

  // the insert is pretty bunk, but i don't want to waste more time on mocking a database

}).call(this);
