// Generated by CoffeeScript 2.4.1
(function() {
  var Item_Interface;

  Item_Interface = class Item_Interface {
    insert(item) {
      return global[item.name] = item;
    }

    find(item_name) {
      return global[item_name];
    }

  };

  exports.Item_Interface = Item_Interface;

}).call(this);
