// Generated by CoffeeScript 2.4.1
(function() {
  var Tax_Interface;

  Tax_Interface = class Tax_Interface {
    // @insert: (tax)->
    // 	global.all_taxes[tax.name] = tax

    // @find: (tax_name)->
    // 	return global.all_taxes[tax_name]
    static get_all() {
      return Object.values(global.all_taxes);
    }

  };

  exports.Tax_Interface = Tax_Interface;

}).call(this);
