// Generated by CoffeeScript 2.4.1
(function() {
  var assert;

  assert = require('assert');

  describe('Array', function() {
    return describe('#indexOf()', function() {
      return it('should return something something something', function() {
        return assert.equal([1, 2, 3].indexOf(4), -1);
      });
    });
  });

}).call(this);
