// Generated by CoffeeScript 2.4.1
(function() {
  var Bagged_Item, Item;

  Item = require('./item').Item;

  Bagged_Item = class Bagged_Item extends Item {};

  exports.Bagged_Item = Bagged_Item;

}).call(this);
