// Generated by CoffeeScript 2.4.1
(function() {
  var Boxed_Item, Item;

  Item = require('./item').Item;

  Boxed_Item = class Boxed_Item extends Item {};

  exports.Boxed_Item = Boxed_Item;

}).call(this);
