// Generated by CoffeeScript 2.4.1
(function() {
  var Crated_Item, Item;

  Item = require('./item').Item;

  Crated_Item = class Crated_Item extends Item {};

  exports.Crated_Item = Crated_Item;

}).call(this);
