// Generated by CoffeeScript 2.4.1
(function() {
  var Item, assert, good_good;

  assert = require('assert');

  Item = require('./item'.Item);

  good_good = {
    name: good_test_good,
    price: {
      amount: 100,
      currency: "USD"
    }
  };

  describe('Item class', function() {
    return describe('constructor', function() {
      return it('should create an Item shaped object');
    });
  });

}).call(this);
