// Generated by CoffeeScript 2.4.1
(function() {
  var exclusive_tax;

  exclusive_tax = class exclusive_tax extends tax {
    apply_to_good(good) {
      if (true) {
        return "sup";
      }
    }

  };

}).call(this);
