// Generated by CoffeeScript 2.4.1
(function() {
  var inclusive_tax, tax;

  tax = requires('./tax').tax;

  inclusive_tax = class inclusive_tax extends tax {
    set_inclusions(inclusions) {
      this.inclusions = inclusions;
    }

    should_apply(item) {
      var apply_it, criterion, i, len, ref;
      apply_it = false;
      ref = this.inclusions;
      for (i = 0, len = ref.length; i < len; i++) {
        criterion = ref[i];
        if (item[criterion] === true) {
          apply_it = true;
          break;
        }
      }
      return apply_it;
    }

  };

  exports.inclusive_tax = inclusive_tax;

}).call(this);
