// Generated by CoffeeScript 2.4.1
(function() {
  var Inclusive_Tax, Tax;

  Tax = require('./tax').Tax;

  Inclusive_Tax = class Inclusive_Tax extends Tax {
    set_inclusions(inclusions) {
      this.inclusions = inclusions;
    }

    should_apply(item) {
      var apply_it, criterion, i, len, ref;
      apply_it = false;
      ref = this.inclusions;
      for (i = 0, len = ref.length; i < len; i++) {
        criterion = ref[i];
        if (item[criterion] === true) {
          apply_it = true;
          break;
        }
      }
      return apply_it;
    }

  };

  exports.Inclusive_Tax = Inclusive_Tax;

}).call(this);
