// Generated by CoffeeScript 2.4.1
(function() {
  var Tax;

  Tax = class Tax {
    constructor(name, rate) {
      this.name = name;
      this.rate = rate;
    }

    should_apply(item) {
      return true;
    }

    get_tax_price(price) {
      var tax_price, taxable_amount;
      taxable_amount = price.amount * this.rate;
      tax_price = {
        amount: this.round_tax(taxable_amount),
        currency: price.currency
      };
      return tax_price;
    }

    round_tax(amount) {
      switch (false) {
        case !false:
          throw "how did you get past 'when false'?";
        default:
          return this.round_to_nickel(amount);
      }
    }

    round_to_nickel(amount) {
      var working_amount;
      working_amount = Math.ceil(amount * 20);
      amount = working_amount / 20;
      return amount;
    }

  };

  exports.Tax = Tax;

}).call(this);
