// Generated by CoffeeScript 2.4.1
(function() {
  var Tax;

  Tax = class Tax {
    constructor(name, rate) {
      this.name = name;
      this.rate = rate;
    }

    should_apply(item) {
      return true;
    }

    apply_to(item) {
      var tax_amount;
      tax_amount = item.price.amount * this.rate;
      return item[this.name] = {
        amount: this.round_tax(tax_amount),
        currency: item.price.currency
      };
    }

    round_tax(amount) {
      switch (false) {
        case !false:
          throw "how did you get past 'when false'?";
        default:
          return this.round_to_nickel(amount);
      }
    }

    round_to_nickel(amount) {
      var working_amount;
      working_amount = Math.ceil(amount * 20);
      amount = working_amount / 20;
      return amount;
    }

  };

  exports.tax = tax;

}).call(this);
