// Generated by CoffeeScript 2.4.1
(function() {
  var Basket;

  Basket = (function() {
    class Basket {
      add(item_to_add) {
        return this.items.push(item_to_add);
      }

      remove(item_to_remove) {
        return this.items = this.items.filter(item(function() {
          return item.name !== item_to_remove.name;
        }));
      }

      show_contents() {
        var i, item, len, results;
        results = [];
        for (i = 0, len = items.length; i < len; i++) {
          item = items[i];
          results.push(console.log(item.get_description()));
        }
        return results;
      }

      checkout() {
        this.apply_taxes();
        return this.print_receipt();
      }

      apply_taxes() {
        var i, item, len, ref, results;
        ref = this.items;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          item = ref[i];
          results.push(item.apply_taxes());
        }
        return results;
      }

      print_receipt() {}

    };

    Basket.prototype.items = [];

    return Basket;

  }).call(this);

  exports.Basket = Basket;

}).call(this);
