// Generated by CoffeeScript 2.4.1
(function() {
  var Price;

  Price = (function() {
    class Price {};

    Price.prototype.amount = 0;

    Price.prototype.currency = "USD";

    return Price;

  }).call(this);

  // this isn't used anywhere, but I noticed I was expecting an object of this shape in a bunch of places
// if js were typed, this would have existed much earlier, and actually be used

}).call(this);
