// Generated by CoffeeScript 2.4.1
(function() {
  var Price;

  Price = class Price {
    constructor(amount = 0, currency = 'USD') {
      this.amount = amount;
      this.currency = currency;
    }

  };

  // is_valid: (price)->

// this isn't used anywhere, but I noticed I was expecting an object of this shape in a bunch of places
// if js were typed, this would have existed much earlier, and actually be used

// exports.Price = Price

}).call(this);
