// Generated by CoffeeScript 2.4.1
(function() {
  var Catalog;

  Catalog = class Catalog {
    constructor(items) {
      this.items = items;
    }

    add_item(item_to_add) {
      return this.items.push(item_to_add);
    }

  };

}).call(this);
