// Generated by CoffeeScript 2.4.1
(function() {
  var Store;

  Store = class Store {
    constructor(catalogs) {
      this.catalogs = catalogs;
    }

    add_catalog(catalog_to_add) {
      return this.catalogs.push(catalog_to_add);
    }

  };

  // remove_catalog: (catalog_to_remove)->
// 	@catalogs = @catalogs.filter catalog-> catalog.name isnt catalog_to_remove.name

}).call(this);
