// Generated by CoffeeScript 2.4.1
(function() {
  var Candy, Good;

  Good = require('./good').Good;

  Candy = (function() {
    class Candy extends Good {};

    Candy.prototype.candy = true;

    return Candy;

  }).call(this);

  exports.Candy = Candy;

}).call(this);
