// Generated by CoffeeScript 2.4.1
(function() {
  var Candy, Good;

  Good = require('./good').Good;

  Candy = class Candy extends Good {
    constructor(name, price, unit_of_measure) {
      super(name, price, unit_of_measure);
      this.candy = true;
    }

  };

  exports.Candy = Candy;

}).call(this);
