// Generated by CoffeeScript 2.4.1
(function() {
  var Candy;

  Candy = (function() {
    class Candy extends Good {};

    Candy.prototype.candy = true;

    return Candy;

  }).call(this);

}).call(this);
