// Generated by CoffeeScript 2.4.1
(function() {
  var Coffee, Good;

  Good = require('./good').Good;

  Coffee = (function() {
    // this file name is kinda silly
    class Coffee extends Good {};

    Coffee.prototype.coffee = true;

    return Coffee;

  }).call(this);

  exports.Coffee = Coffee;

}).call(this);
