// Generated by CoffeeScript 2.4.1
(function() {
  // this file name is kinda silly
  var coffee;

  coffee = (function() {
    class coffee extends good {};

    coffee.prototype.coffee = true;

    return coffee;

  }).call(this);

}).call(this);
