// Generated by CoffeeScript 2.4.1
(function() {
  // this file name is kinda silly
  var Coffee;

  Coffee = (function() {
    class Coffee extends Good {};

    Coffee.prototype.coffee = true;

    return Coffee;

  }).call(this);

}).call(this);
