// Generated by CoffeeScript 2.4.1
(function() {
  var good;

  good = class good {
    constructor(description) {
      this.description = description;
      this.price;
    }

    apply_taxes(tax_array) {
      var i, len, results, tax;
      results = [];
      for (i = 0, len = tax_array.length; i < len; i++) {
        tax = tax_array[i];
        results.push("sup");
      }
      return results;
    }

  };

}).call(this);
