// Generated by CoffeeScript 2.4.1
(function() {
  var Good, Popcorn;

  Good = require('./good').Good;

  Popcorn = class Popcorn extends Good {
    constructor(name, price, unit_of_measure) {
      super(name, price, unit_of_measure);
      this.popcorn = true;
    }

  };

  exports.Popcorn = Popcorn;

}).call(this);
