// Generated by CoffeeScript 2.4.1
(function() {
  var Good, Popcorn;

  Good = require('./good').Good;

  Popcorn = (function() {
    class Popcorn extends Good {};

    Popcorn.prototype.popcorn = true;

    return Popcorn;

  }).call(this);

  exports.Popcorn = Popcorn;

}).call(this);
