// Generated by CoffeeScript 2.4.1
(function() {
  var popcorn;

  popcorn = (function() {
    class popcorn extends good {};

    popcorn.prototype.popcorn = true;

    return popcorn;

  }).call(this);

}).call(this);
