// Generated by CoffeeScript 2.4.1
(function() {
  var Bagged_Item, Item;

  Item = require('./item').Item;

  Bagged_Item = (function() {
    class Bagged_Item extends Item {};

    Bagged_Item.prototype.packaging = "bag";

    return Bagged_Item;

  }).call(this);

  // constructor: (good, quantity=1)->
  // 	super(good, quantity)
  exports.Bagged_Item = Bagged_Item;

}).call(this);
