// Generated by CoffeeScript 2.4.1
(function() {
  var Bottled_Item, Item;

  Item = require('./item').Item;

  Bottled_Item = (function() {
    class Bottled_Item extends Item {};

    Bottled_Item.prototype.packaging = "bottle";

    return Bottled_Item;

  }).call(this);

  // constructor: (good, quantity=1)->
  // 	super(good, quantity)
  exports.Bottled_Item = Bottled_Item;

}).call(this);
