// Generated by CoffeeScript 2.4.1
(function() {
  var Bottled_Item, Item;

  Item = require('./item').Item;

  Bottled_Item = class Bottled_Item extends Item {};

  exports.Bottled_Item = Bottled_Item;

}).call(this);
