// Generated by CoffeeScript 2.4.1
(function() {
  var Boxed_Item, Item;

  Item = require('./item').Item;

  Boxed_Item = (function() {
    class Boxed_Item extends Item {};

    Boxed_Item.prototype.packaging = "box";

    return Boxed_Item;

  }).call(this);

  // constructor: (good, quantity=1)->
  // 	super(good, quantity)
  exports.Boxed_Item = Boxed_Item;

}).call(this);
