// Generated by CoffeeScript 2.4.1
(function() {
  var Item, Tax_Interface;

  Tax_Interface = require('./../../data_interfaces/tax_interface').Tax_Interface;

  Item = class Item {
    constructor(good, quantity = 1) {
      this.good = good;
      this.quantity = quantity;
      if (this.good != null) {
        this.set_price();
      } else {
        throw "A Good is required to create an Item";
      }
    }

    get_description() {
      if (this.description == null) {
        this.description = this.good.name + " at " + this.price;
      }
      return this.description;
    }

    set_price() {
      var ref;
      return this.price = this.quantity * ((ref = this.good.price) != null ? ref.amount : void 0);
    }

    get_price() {
      return this.price;
    }

    flag_imported() {
      return this.imported = true;
    }

    apply_taxes() {
      var i, len, ref, results, tax;
      ref = Tax_Interface.get_all();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        tax = ref[i];
        if (tax.should_apply(this)) {
          results.push(tax.apply_to(this));
        } else {
          results.push(void 0);
        }
      }
      return results;
    }

  };

  exports.Item = Item;

}).call(this);
