// Generated by CoffeeScript 2.4.1
(function() {
  var demo_basket_1, demo_basket_2, demo_basket_3;

  demo_basket_1 = function() {
    var basket;
    basket = new basket();
    basket.add(skittles_16);
    basket.add(walkman);
    basket.add(popcorn);
    return basket.checkout();
  };

  demo_basket_2 = function() {
    var basket;
    basket = new basket();
    basket.add(coffee_vh);
    basket.add(vespa);
    return basket.checkout();
  };

  demo_basket_3 = function() {
    var basket;
    basket = new basket();
    basket.add(snickers_a);
    basket.add(discman);
    basket.add(wine);
    basket.add(coffee_300);
    return basket.checkout();
  };

  exports.demo_commands = {demo_basket_1, demo_basket_2, demo_basket_3};

}).call(this);
