// Generated by CoffeeScript 2.4.1
(function() {
  var Basket, Item_Interface, demo_basket_1, demo_basket_2, demo_basket_3;

  Basket = require('./classes/basket').Basket;

  Item_Interface = new require('./data_interfaces/item_interface').Item_Interface;

  console.log(Item_Interface);

  demo_basket_1 = function() {
    var basket;
    console.log(global);
    console.log(global.global);
    basket = new Basket();
    basket.add(Item_Interface.find("skittles_16"));
    basket.add(Item_Interface.find("walkman"));
    basket.add(Item_Interface.find("popcorn"));
    return basket.checkout();
  };

  demo_basket_2 = function() {
    var basket;
    basket = new Basket();
    basket.add(Item_Interface.find("coffee_vh"));
    basket.add(Item_Interface.find("vespa"));
    return basket.checkout();
  };

  demo_basket_3 = function() {
    var basket;
    basket = new Basket();
    basket.add(Item_Interface.find("snickers_a"));
    basket.add(Item_Interface.find("discman"));
    basket.add(Item_Interface.find("wine"));
    basket.add(Item_Interface.find("coffee_300"));
    return basket.checkout();
  };

  exports.demo_commands = {demo_basket_1, demo_basket_2, demo_basket_3};

}).call(this);
