// Generated by CoffeeScript 2.4.1
(function() {
  ({
    demo_basket_1: function() {
      var basket;
      basket = new basket;
      basket.add(skittles_16);
      basket.add(walkman);
      basket.add(popcorn);
      return basket.checkout;
    },
    demo_basket_2: function() {
      basket.add(coffee_vh);
      basket.add(vespa);
      return basket.checkout;
    },
    demo_basket_3: function() {
      basket.add(snickers_a);
      basket.add(discman);
      basket.add(wine);
      basket.add(coffee_300);
      return basket.checkout;
    }
  });

}).call(this);
