// Generated by CoffeeScript 2.4.1
(function() {
  var assert, bad_command_message, input_handler, recognized_commands, test_message;

  assert = require('assert');

  input_handler = require('./main').input_handler;

  test_message = "ran known command";

  recognized_commands = {
    test_1: function() {
      return test_message;
    }
  };

  bad_command_message = "ran mystery command";

  describe('input_handler', function() {
    it('should handle null', function() {
      return input_handler(null);
    });
    it('should run test_1() when fed "test_1"', function() {
      return assert.strictEqual(input_handler("test_1"), test_message);
    });
    return it('should return an error message when fed a command it does not recognize', function() {
      return assert.strictEqual(input_handler("test_Z"), bad_command_message);
    });
  });

}).call(this);
