// Generated by CoffeeScript 2.4.1
(function() {
  // initialize_goods
  // initialize_catalog
  // initialize_taxes
  console.log('Howdy\nTry typing the commands:\n"demo_basket_1()"\n"demo_basket_2()"\n"demo_basket_3()"\nor try your luck at "custom_basket()" (beta)');

}).call(this);
